(setq package-archives
      '(("gnu" . "http://elpa.gnu.org/packages/")
        ("org" . "http://orgmode.org/elpa/")
        ("melpa-stable" . "http://stable.melpa.org/packages/")
        ("melpa" . "http://melpa.org/packages/")))

(require 'package)
(setq package-enable-at-startup nil)
(package-initialize)

;; Bootstrap `use-package'
(unless (package-installed-p 'use-package)
  (package-refresh-contents)
  (package-install 'use-package))

(let ((default-directory "~/.emacs.d/"))
  (normal-top-level-add-subdirs-to-load-path))

(use-package slime)
(use-package smex)
(use-package auto-complete)
(use-package ido)
(use-package ido-completing-read+)
(use-package visible-mark)
(use-package highline)
(use-package dired)
(use-package dired-efap)
(use-package exec-path-from-shell)
(use-package flycheck)
(use-package misc)
(use-package simp)
(use-package move-dup)
(use-package expand-region)
(use-package winner)
(use-package midnight)
(use-package isearch-symbol-at-point)
(use-package multiple-cursors)
(use-package itail)
(use-package powerline)
(use-package smart-indent-rigidly)
(use-package tide)
(use-package emojify
  :config
  (global-emojify-mode))
(use-package magit)
(use-package my-theme)
(use-package my-isearch)
(use-package my-backup)
(use-package my-autoloads)
(use-package my-add-to-lists)
(use-package my-project-definitions)
(use-package my-functions)
(use-package my-initializers)
(use-package my-keybindings)
(use-package my-hooks)
(use-package my-settings)
